import React, { useState } from 'react';
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { CheckSquare, Plus, Calendar, Clock, AlertCircle } from 'lucide-react';
import { base44 } from "@/api/base44Client";
import { toast } from 'sonner';
import { format, parseISO } from 'date-fns';

export default function ProducerTaskItem({ task }) {
    const [isAdded, setIsAdded] = useState(false);
    const [isLoading, setIsLoading] = useState(false);

    const handleAddTask = async () => {
        setIsLoading(true);
        try {
            await base44.entities.FamilyTask.create({
                title: task.task,
                description: `${task.detail || ''}\n\nGenerated by Sequins Producer.\nDepartment: ${task.department}\nDue Milestone: ${task.due_milestone}`,
                status: 'pending',
                category: 'event',
                priority: task.priority === 'critical' ? 'high' : (task.priority === 'high' ? 'medium' : 'low'),
                is_shared: true,
                due_date: task.due_date || undefined
            });
            setIsAdded(true);
            toast.success("Task added to project board");
        } catch (e) {
            console.error(e);
            toast.error("Failed to add task");
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <button 
            onClick={!isAdded && !isLoading ? handleAddTask : undefined}
            disabled={isAdded || isLoading}
            className={`w-full text-left transition-all duration-200 group relative overflow-hidden ${
                isAdded 
                    ? 'bg-green-50 border-green-200 opacity-60' 
                    : 'bg-white hover:border-indigo-300 hover:shadow-md border-gray-200'
            } rounded-xl p-3 border shadow-sm flex items-start gap-3`}
        >
            {isAdded && (
                <div className="absolute inset-0 flex items-center justify-center bg-white/50 backdrop-blur-[1px] z-10">
                        <div className="bg-green-100 text-green-700 px-3 py-1 rounded-full text-xs font-bold flex items-center gap-1">
                            <CheckSquare className="w-3 h-3" /> Added
                        </div>
                </div>
            )}

            <div className={`mt-1 w-2 h-2 rounded-full shrink-0 ${
                task.priority === 'critical' ? 'bg-red-500' : 
                task.priority === 'high' ? 'bg-orange-400' : 'bg-green-400'
            }`} />
            <div className="flex-1">
                <div className="font-medium text-sm text-[#333333] leading-snug group-hover:text-indigo-700 transition-colors">
                    {task.task}
                </div>
                
                {/* Timeline Info */}
                {task.due_date && (
                    <div className="flex items-center gap-3 mt-2 text-xs text-gray-500">
                        <div className={`flex items-center gap-1 font-medium ${task.days_from_now < 7 ? 'text-orange-600' : ''}`}>
                            <Calendar className="w-3 h-3" />
                            {format(parseISO(task.due_date), 'MMM d')}
                        </div>
                        {task.days_from_now !== undefined && (
                            <div className="flex items-center gap-1">
                                <Clock className="w-3 h-3" />
                                {task.days_from_now < 0 ? (
                                    <span className="text-red-500 font-bold">Overdue</span>
                                ) : (
                                    <span>In {task.days_from_now} days</span>
                                )}
                            </div>
                        )}
                    </div>
                )}

                <div className="flex items-center gap-2 mt-2">
                    <Badge variant="secondary" className="text-[10px] h-5 px-1.5 font-normal bg-gray-100 text-gray-500 border border-gray-200 group-hover:border-indigo-100 group-hover:bg-indigo-50 group-hover:text-indigo-600">
                        {task.department}
                    </Badge>
                    {!isAdded && (
                        <span className="ml-auto text-xs font-bold text-indigo-600 opacity-0 group-hover:opacity-100 transition-opacity flex items-center gap-1">
                            <Plus className="w-3 h-3" /> Add
                        </span>
                    )}
                </div>
            </div>
        </button>
    );
}